[mypy]
strict = True
ignore_missing_imports = True

[mypy-pydub.*]
ignore_missing_imports = True

[mypy-resemblyzer.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-torchaudio.*]
ignore_missing_imports = True

[mypy-vosk.*]
ignore_missing_imports = True

[mypy-pyannote.*]
ignore_missing_imports = True

[mypy-diarize.*]
ignore_missing_imports = True