[pytest]
norecursedirs = .* venv env *.egg-info jobs.db-shm jobs.db-wal
filterwarnings =
    ignore:.*binary_dilation.*:DeprecationWarning
    ignore:.*torchaudio.sox_effects.sox_effects.apply_effects_file.*:UserWarning
    ignore:.*torchcodec.*:UserWarning
    ignore:.*TensorFloat-32.*:UserWarning
    ignore:std\(\). degrees of freedom is <= 0:UserWarning
