[pytest]
# Discovery
testpaths = tests
python_files = test_*.py

# Exclusions (OK chez toi)
norecursedirs = .* venv env *.egg-info jobs.db-shm jobs.db-wal

# Options globales
addopts =
    -q
    --strict-markers
    --tb=short
    --maxfail=1
    --cache-clear
    --cov=backend
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=50

# Discipline des tests
xfail_strict = true

# Logs (utile en CI / debug)
log_cli = true
log_cli_level = INFO

# Warnings
filterwarnings =
    error
    ignore:.*binary_dilation.*:DeprecationWarning
    ignore:.*torchaudio.sox_effects.sox_effects.apply_effects_file.*:UserWarning
    ignore:.*torchcodec.*:UserWarning
    ignore:.*TensorFloat-32.*:UserWarning
    ignore:std\(\). degrees of freedom is <= 0:UserWarning