# This test has been removed because the client‑side JavaScript handling
# of CPU‑only mode has been replaced by server‑side rendering.
# The functionality is now verified through integration tests of the
# HTML response generated by the server.